include: package:lint_hard/all.yaml
# include: package:lints/recommended.yaml


analyzer:
#  language:
#     strict-casts: true
#     strict-inference: true
#     strict-raw-types: true

  exclude:
    - lib/src/pub
