name: onepub
version: 1.1.0
homepage: https://github.com/noojee/onepub.dev
description: Command line tools for onepub.dev including a replacement pub command.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  cli_util: ^0.3.5
  dcli: ^1.16.2
  http_multi_server: ^3.0.1
  oauth2: ^2.0.0
  pub_semver: ^2.1.0
  shelf: ^1.2.0
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.20.1
executables: 
  onepub: 
  opub: 
