name: onepub
version: 4.2.0
homepage: https://onepub.dev
documentation: https://docs.onepub.dev
description: Command line tools for the OnePub private Dart/Flutter repository.
repository: https://github.com/onepub-dev/onepub
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  # _fe_analyzer_shared: ^68.0.0
  
  archive: ^3.6.0
  args: ^2.5.0
  async: 2.11.0
  basic_utils: 5.7.0
  boolean_selector: 2.1.1
  characters: 1.3.0
  charcode: 1.3.1
  chunked_stream: 1.4.2
  circular_buffer: 0.11.0
  cli_util: 0.4.1
  clock: 1.1.1
  collection: ^1.19.0
  convert: 3.1.1
  coverage: ^1.8.0
  crypto: 3.0.3
  csv: ^6.0.0
  dart_console: ^4.1.0
  dcli_core: ^5.0.0
  dcli_input: ^5.0.0
  dcli_terminal: ^5.0.0
  equatable: 2.0.5
  ffi: ^2.1.2
  file: 7.0.0
  frontend_server_client: ^4.0.0
  functional_data: ^1.2.0
  glob: 2.1.2
  globbing: 1.0.0
  http: ^1.2.1
  http_multi_server: 3.2.1
  http_parser: ^4.1.0
  ini: 2.1.0
  intl: ^0.19.0
  io: 1.0.4
  js: 0.7.1
  json2yaml: 3.0.1
  json_annotation: ^4.9.0
  lists: 1.0.1
  logging: 1.2.0
  meta: ^1.15.0
  mime: 1.0.5
  node_preamble: 2.0.2
  oauth2: 2.0.2
  package_config: 2.1.0
  path: 1.9.0
  pointycastle: ^3.9.1
  pool: 1.5.1
  posix: 6.0.1
  pub_semver: 2.1.4
  pubspec_lock: 3.0.2
  pubspec_manager: ^1.0.0
  quiver: 3.2.1
  random_string: 2.3.1
  scope: ^4.1.1
  settings_yaml: ^8.1.0
  shelf: ^1.4.2
  source_map_stack_trace: 2.1.1
  source_maps: 0.10.12
  source_span: 1.10.0
  stack_trace: 1.11.1
  stacktrace_impl: 2.3.0
  stream_channel: 2.1.2
  string_scanner: ^1.3.0
  strings: ^3.1.2
  sum_types: 0.3.5
  system_info2: 4.0.0
  term_glyph: 1.2.1
  typed_data: 1.3.2
  uri: 1.0.0
  url_builder: 2.0.0
  usage: 4.1.1
  uuid: ^4.4.0
  validators2: 5.0.0
  watcher: 1.1.0
  web_socket_channel: ^3.0.0
  webkit_inspection_protocol: 1.2.1
  win32: ^5.3.0
  yaml: 3.1.2
  yaml_edit: ^2.2.1
dev_dependencies:
  analyzer: ^6.5.0
  dcli: ^5.0.0
  lint_hard: ^5.0.0
  lints: ^4.0.0
  matcher: 0.12.16+1
  shelf_packages_handler: 3.0.2
  shelf_static: 1.1.2
  shelf_web_socket: ^2.0.0
  test: ^1.25.5
  test_api: ^0.7.1
  test_core: ^0.6.2
  vm_service: ^14.2.2
executables:
  onepub:
  opub:
platforms:
  linux:
  macos:
  windows:
false_secrets:
  - lib/src/pub/validator/leak_detection.dart
  - lib/src/pub/oauth2.dart

