name: onepub
version: 3.2.1
homepage: https://onepub.dev
documentation: https://docs.onepub.dev
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: Command line tools for the OnePub private Dart/Flutter repository.
repository: https://github.com/onepub-dev/onepub
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  _fe_analyzer_shared: 26.0.0
  analyzer: 2.3.0
  archive: 3.3.0
  args: 2.3.1
  async: 2.8.2
  basic_utils: 3.8.0
  boolean_selector: 2.1.0
  charcode: 1.3.1
  chunked_stream: 1.4.1
  circular_buffer: 0.9.1
  cli_util: 0.3.5
  collection: 1.15.0
  convert: 3.1.0
  coverage: 1.0.3
  crypto: 3.0.1
  csv: 5.0.1
  dart_console: 1.0.0
  dcli: 1.22.1
  dcli_core: 1.22.1
  equatable: 2.0.3
  ffi: 1.2.1
  file: 6.1.4
  file_utils: 1.0.1
  frontend_server_client: 2.1.2
  glob: 2.0.1
  globbing: 1.0.0
  http: 0.13.3
  http_multi_server: 3.0.1
  http_parser: 4.0.0
  ini: 2.1.0
  io: 1.0.3
  js: 0.6.3
  json_annotation: 4.1.0
  logging: 1.0.2
  meta: 1.8.0
  mime: 1.0.2
  node_preamble: 2.0.1
  oauth2: 2.0.0
  package_config: 2.1.0
  path: 1.8.1
  pedantic: 1.11.1
  pointycastle: 3.6.0
  pool: 1.5.0
  posix: 2.2.3
  pub_semver: 2.1.2
  pubspec2: 2.4.2
  random_string: 2.3.1
  scope: 3.0.0
  settings_yaml: 3.5.1
  shelf: 1.2.0
  source_map_stack_trace: 2.1.0
  source_maps: 0.10.10
  source_span: 1.8.1
  stack_trace: 1.10.0
  stacktrace_impl: 2.3.0
  stream_channel: 2.1.0
  string_scanner: 1.1.1
  strings_xxx: 1.0.0
  system_info2: 2.0.4
  term_glyph: 1.2.1
  typed_data: 1.3.0
  url_builder: 1.0.0
  usage: 4.0.2
  uuid: 3.0.6
  validators2: 3.0.0
  vin_decoder: 0.2.1-nullsafety
  watcher: 1.0.0
  web_socket_channel: 2.2.0
  webkit_inspection_protocol: 1.1.0
  win32: 2.0.5
  yaml: 3.1.0
  yaml_edit: 2.0.2
dev_dependencies: 
  lint_hard: 1.0.4
  matcher: 0.12.11
  shelf_packages_handler: 3.0.0
  shelf_static: 1.1.0
  shelf_web_socket: 1.0.1
  test: 1.17.12
  test_api: 0.4.3
  test_core: 0.4.2
  vm_service: 7.5.0
executables: 
  onepub: 
  opub: 
platforms: 
  linux: 
  macos: 
  windows: 
false_secrets: 
  - lib/src/pub/validator/leak_detection.dart
