name: onepub
version: 1.0.1
homepage: https://github.com/noojee/onepub.dev
description: Command line tools for onepub.dev
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  dcli: ^1.15.5
dev_dependencies: 
  lints: ^1.0.0
executables: 
  onepub: 
  pub: 
  pubd: 
