name: onepub
version: 0.0.1
homepage: https://onepub.dev
description: Command line tools for onepub.dev
environment: 
  sdk: '>=2.14.0 <3.0.0'
dev_dependencies: 
  lints: ^1.0.0
executable: 
  onpub: null
