name: onepub
version: 3.1.0
homepage: https://onepub.dev
documentation: https://docs.onepub.dev
description: Command line tools for the OnePub private Dart/Flutter repository.
repository: https://github.com/onepub-dev/onepub
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  _fe_analyzer_shared: ^52.0.0
  analyzer: ^5.4.0
  archive: ^3.3.7
  args: 2.3.1
  async: ^2.11.0
  basic_utils: ^5.5.4
  boolean_selector: ^2.1.1
  charcode: 1.3.1
  chunked_stream: 1.4.1
  circular_buffer: ^0.11.0
  cli_util: 0.3.5
  collection: ^1.17.2
  convert: ^3.1.1
  coverage: ^1.6.3
  crypto: ^3.0.3
  csv: 5.0.1
  dart_console2: 3.0.0
  dcli: 2.2.0
  dcli_core: 2.2.0
  equatable: ^2.0.5
  ffi: ^2.0.1
  file: 6.1.4
  file_utils: 1.0.1
  frontend_server_client: ^3.2.0
  glob: ^2.1.1
  globbing: 1.0.0
  http: ^0.13.6
  http_multi_server: ^3.2.1
  http_parser: ^4.0.2
  ini: 2.1.0
  io: 1.0.3
  js: ^0.6.7
  json_annotation: ^4.8.1
  logging: ^1.1.1
  meta: ^1.9.1
  mime: ^1.0.4
  node_preamble: 2.0.1
  oauth2: ^2.0.1
  package_config: 2.1.0
  path: ^1.8.3
  pedantic: 1.11.1
  pointycastle: ^3.7.3
  pool: ^1.5.1
  posix: ^5.0.0
  pub_semver: ^2.1.4
  pubspec2: 2.4.2
  random_string: 2.3.1
  scope: 3.0.0
  settings_yaml: ^5.0.0
  shelf: ^1.4.1
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12
  source_span: ^1.10.0
  stack_trace: ^1.11.0
  stacktrace_impl: 2.3.0
  stream_channel: ^2.1.1
  string_scanner: ^1.2.0
  strings_xxx: 1.0.0
  system_info2: ^3.0.2
  term_glyph: 1.2.1
  typed_data: ^1.3.2
  url_builder: 1.0.0
  usage: ^4.1.1
  uuid: ^3.0.7
  validators2: ^4.0.0
  watcher: ^1.0.2
  web_socket_channel: ^2.4.0
  webkit_inspection_protocol: ^1.2.0
  win32: ^4.1.4
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
dev_dependencies: 
  lint_hard: 1.0.4
  matcher: 0.12.11
  shelf_packages_handler: ^3.0.2
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  test: ^1.23.1
  test_api: ^0.4.18
  test_core: ^0.4.24
  vm_service: ^10.1.2
executables: 
  onepub: 
  opub: 
platforms: 
  linux: 
  macos: 
  windows: 
false_secrets: 
  - lib/src/pub/validator/leak_detection.dart
