name: onepub
version: 1.1.10
homepage: https://github.com/onepub-dev/onepub
description: Command line tools for onepub.dev including a replacement pub command.
environment: 
  sdk: '>=2.12.1 <3.0.0'
dependencies: 
  args: 2.3.0
  basic_utils: 3.8.0
  dcli: 1.20.1
  equatable: 2.0.3
  glob: 2.0.1
  http_multi_server: 3.0.1
  json_annotation: 4.1.0
  meta: 1.7.0
  oauth2: 2.0.0
  path: 1.8.1
  pub_semver: 2.1.0
  settings_yaml: 3.4.1
  shelf: 1.2.0
  stack_trace: 1.10.0
  usage: 4.0.2
  validators2: 3.0.0
  yaml: 3.1.0
  analyzer: 2.3.0
  collection: 1.15.0
  source_span: 1.8.1
  http: 0.13.3
  pool: 1.5.0
  frontend_server_client: 2.1.2
  http_parser: 4.0.0
  crypto: 3.0.1
  async: 2.8.2
  typed_data: 1.3.0
  pedantic: 1.11.1
  yaml_edit: 2.0.2
  watcher: 1.0.0
  win32: 2.0.5
  pubspec: ^2.1.0
  cli_util: ^0.3.5
dev_dependencies: 
  lint_hard: ^1.0.0
  test: 1.17.12
dependency_overrides: 
  lint_hard: 
    path: ../../lint_hard
executables: 
  onepub: 
  opub: 
platforms: 
  linux: null
  macos: null
  windows: null
false_secrets: 
  - lib/src/pub/validator/leak_detection.dart
