# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: compile

on:
  push:
    branches: [ main ]
    # the release proces will fail if we run it without a tag.
    tags:
      - 'v*.*.*'  # only release when a tag is pushed of the form vx.x.x

jobs: 
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
          
      # you can reference the tagged version via 
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}          

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      - name: Delete Test dir so analyze runs
        run: rm -r test

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
        
      - name: Create release dir
        run: mkdir bin/${{ matrix.os }}

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run compile opub
        run: dart compile exe bin/opub.dart -o bin/${{ matrix.os }}/opub

      - name: Run compile onepub
        run: dart compile exe bin/onepub.dart -o bin/${{ matrix.os }}/onepub
        
      - name: Release opub and onepub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          name: ${{ matrix.os }}/${{github.ref_name}}
          files: |
            bin/${{ matrix.os }}/opub
            bin/${{ matrix.os }}/onepub
          
        


